Add custom slippage tolerance
DeFiCh/wallet pull request #1174
Opened 2021-10-27 00:28 UTC by pierregee

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
- This will help the user set a custom slippage 

#### Which issue(s) does this PR fixes?:

Fixes #636

#### Additional comments?:

#### Developer Checklist:

- [x] Read your code changes at least once
- [x] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [x] No console errors on web
- [x] Tested on Light mode and Dark mode*
- [x] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [x] Added e2e tests*
- [x] Added translations*

2021-10-31 02:58 UTC, thedoublejay commented on mobile-app/app/screens/AppNavigator/screens/Dex/PoolSwap/PoolSwapScreen.tsx
> +  const [slippage, setSlippage] = useState(new BigNumber(3))
@ivan-zynesis @pierregee We have it as 3% since our release. Since we don't have complaints for now, I suggest we keep it first.

2021-10-31 03:20 UTC, thedoublejay requested changes
It doesn't scroll on iPhone SE when you click on Custom. Cannot view Submit

2021-11-01 05:07 UTC, pierregee commented
> It doesn't scroll on iPhone SE when you click on Custom. Cannot view Submit

@thedoublejay Updated! I added a ScrollView.

**Additional Info:** 
 - Android and iOS seems to be responding differently with `ScrollView` inside the `BottomSheet` so I added `KeyboardAvoidingView` to handle space at the top of the keyboard (tested with iPhone SE Simulator)
 - Opted out of using the `react-native-bottom-sheet/BottomSheetScrollView` because it has more erratic behaviour

See image below if `KeyboardAvoidingView` is NOT added (One Plus Nord 2)
![image](https://user-images.githubusercontent.com/13292662/139623849-e4c19b24-9eb4-4960-a3e8-6add10d50990.png)

2021-12-23 04:30 UTC, thedoublejay approved these changes

2021-12-23 05:09 UTC, merged