Collateral tokens usd price in vault details pages
DeFiCh/wallet pull request #1629
Opened 2021-12-08 17:27 UTC by fullstackninja864

#### What kind of PR is this?:

/kind

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2021-12-09 00:59 UTC, thedoublejay requested changes

2021-12-09 00:59 UTC, thedoublejay commented on mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/components/CollateralsTab.tsx
> +    dispatch(fetchCollateralTokens({ client }))
Do we need to add this here? We're already fetching it on the first page

2021-12-09 01:00 UTC, thedoublejay requested changes
![Screenshot_20211209-085653_Expo Go](https://user-images.githubusercontent.com/25013382/145315258-048e967d-9501-4675-aae9-867ad156e50f.jpg)

2021-12-09 05:31 UTC, pierregee commented on mobile-app/app/screens/AppNavigator/screens/Loans/components/AddOrRemoveCollateralForm.tsx
> +                    style={tailwind('text-xs')}
Fix for alignment in android:
```suggestion
                    style={tailwind('text-xs leading-5')}
```

2021-12-13 05:18 UTC, thedoublejay requested changes

2021-12-13 05:18 UTC, thedoublejay commented on mobile-app/app/screens/AppNavigator/screens/Loans/components/AddOrRemoveCollateralForm.tsx
> +          <Text>{' '}</Text>
Can we use margin here?

2021-12-13 08:43 UTC, thedoublejay submitted a review, later dismissed

2021-12-14 02:17 UTC, kyleleow submitted a review, later dismissed

2021-12-17 04:43 UTC, thedoublejay approved these changes

2021-12-17 06:57 UTC, thedoublejay approved these changes

2021-12-17 06:57 UTC, merged