`auction` - add bid history tab in auction detail
DeFiCh/wallet pull request #1899
Opened 2022-01-11 16:47 UTC by kyleleow

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
- To display bid history of an auction batch
- To simplify tab enum used for `<Tabs>`, since values of each enum is not used

#### Which issue(s) does this PR fixes?:

Fixes #1829 

#### Additional comments?:
- Will implement e2e in a diff PR, tracked in #1898 

#### Developer Checklist:

- [x] Read your code changes at least once
- [x] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [x] No console errors on web
- [x] Tested on Light mode and Dark mode*
- [x] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [x] Added translations*

2022-01-11 18:56 UTC, kyleleow commented on mobile-app/app/screens/AppNavigator/screens/Auctions/helpers/SecondstoHm.ts
> +export function secondsToTimeAgo (d: number): string {
@pierregee can you help to check if we can refactor the logic here and with `secondsToHmDisplay()`?

2022-03-02 02:29 UTC, pierregee requested changes

2022-03-02 08:08 UTC, kyleleow commented on mobile-app/app/screens/AppNavigator/screens/Auctions/components/BidHistory.tsx
> +        <ActiveUSDValue price={new BigNumber(props.bidAmount).multipliedBy(props.loanActivePrice)} />
updated

2022-03-02 08:09 UTC, kyleleow commented on mobile-app/app/screens/AppNavigator/screens/Auctions/components/BidHistory.tsx
> +    <ThemedFlatList
added arbitrary padding for non-mobile

2022-03-02 08:10 UTC, kyleleow commented on mobile-app/cypress/integration/functional/wallet/auctions/auctions.spec.ts
> +  // const recoveryWords: string[] = []
updated

2022-03-02 11:06 UTC, fullstackninja864 submitted a review, later dismissed

2022-03-03 02:47 UTC, thedoublejay requested changes

2022-03-03 02:47 UTC, thedoublejay commented on mobile-app/app/screens/AppNavigator/screens/Auctions/components/BidHistory.tsx
> +          light={tailwind('bg-blue-500 text-white')}
Should this be only blue when it's the latest build? Based from the latest designs

![image](https://user-images.githubusercontent.com/25013382/156486346-953ebd0b-8c49-41ab-9c5c-b6a09282e8ad.png)

2022-03-03 04:05 UTC, kyleleow commented
Reverted the padding changes on `tabs` component, will track the cropped tab label in another [issue](https://github.com/DeFiCh/wallet/issues/2311)

2022-03-03 07:23 UTC, thedoublejay approved these changes

2022-03-03 07:23 UTC, merged