feature(ui-ux): add USD value for DFI
DeFiCh/wallet pull request #2007
Opened 2022-01-26 05:58 UTC by thedoublejay

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #2003 

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-01-26 11:36 UTC, pierregee approved these changes

2022-01-26 12:02 UTC, pierregee approved these changes

2022-01-27 03:04 UTC, kyleleow requested changes

2022-01-27 03:04 UTC, kyleleow commented on mobile-app/app/screens/AppNavigator/screens/Balances/BalancesScreen.tsx
> +              <View key={item.symbol} style={tailwind('p-2 pb-1.5')}>
The spacing is wider on figma, and to align vertically with DFI balance card
Need to readjust the padding value here

![image](https://user-images.githubusercontent.com/40191153/151284017-877ce624-ec19-411b-a598-ada4ff3989e2.png)

2022-01-27 03:26 UTC, kyleleow approved these changes
Edge cases and ui issues will be tracked on separate issue

2022-01-27 03:27 UTC, merged