feature(core): display banner for outages and maintenances
DeFiCh/wallet pull request #2150
Opened 2022-02-10 03:44 UTC by pierregee

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
- The purpose of this is to have automatic updates in the event of downtime

#### Which issue(s) does this PR fixes?:

Fixes #2058

#### Additional comments?:
- The message for partial outage, scheduled maintenance and major outage is only a placeholder

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-02-14 04:17 UTC, kyleleow requested changes
One non-blocking comment on code refactoring. Tested on iOS and android devices

2022-02-14 06:33 UTC, kyleleow requested changes

2022-02-14 06:33 UTC, kyleleow commented on mobile-app/app/screens/AppNavigator/screens/Balances/hooks/DefichainStatus.ts
> +      'zh-Hant': `將在  ${scheduledForDate} 進行定期維護. 服務將在 ${scheduledUntilDate} 恢復`,
```suggestion
      'zh-Hant': `將在 ${scheduledForDate} 進行定期維護. 服務將在 ${scheduledUntilDate} 恢復`,
```

2022-02-14 06:45 UTC, kyleleow approved these changes

2022-02-15 02:04 UTC, thedoublejay approved these changes

2022-02-15 02:04 UTC, merged