feature(iu-ux): `balances` - sort tokens based on USD value
DeFiCh/wallet pull request #2151
Opened 2022-02-10 04:03 UTC by chloezxyy

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #2089

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-02-10 06:30 UTC, pierregee commented on mobile-app/app/screens/AppNavigator/screens/Balances/BalancesScreen.tsx
> +    const sortedUsdAmt = dstTokens.sort((a, b) => parseInt(b.usdAmount.toFixed(8)) - parseInt(a.usdAmount.toFixed(8)))
![image](https://user-images.githubusercontent.com/13292662/153350292-382d882f-31f8-4795-bb75-8bdbf8e9b539.png)

`parseInt` would remove the decimal points, could you check on how you can sort it with BigNumber funcs?

2022-02-10 08:45 UTC, thedoublejay requested changes

2022-02-10 08:45 UTC, thedoublejay commented on mobile-app/app/screens/AppNavigator/screens/Balances/BalancesScreen.tsx
> +    const sortedUsdAmt = dstTokens.sort((a, b) => parseFloat(b.usdAmount.toFixed(8)) - parseFloat(a.usdAmount.toFixed(8)))
Just chain this with the `.map`. `dstTokens.sort.map`

2022-02-14 05:28 UTC, kyleleow commented
Can we wrap `tokens.reduce()` with `useCallback()` at https://github.com/DeFiCh/wallet/blob/1ae6ea699a9fba981b0574dc04d0920d53be2db6/mobile-app/app/screens/AppNavigator/screens/Balances/BalancesScreen.tsx#L82 for performance sake?

2022-02-14 05:32 UTC, kyleleow commented on mobile-app/cypress/integration/functional/wallet/balances/balances.spec.ts
> +    // dLTC will be displayed at the top of the card on first topup
```suggestion
    // dETH will be displayed at the top of the card on first topup
```

2022-02-15 02:33 UTC, thedoublejay approved these changes

2022-02-15 02:41 UTC, merged