updated balances to send flow
DeFiCh/wallet pull request #223
Opened 2021-07-01 11:01 UTC by thedoublejay

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
Updated UX for Send
1. Click on Balances Item 
2. Redirect to Token Detail Page
3. Ability to
   - Send (not available for DFI Token)
   - Receive (not available for DFI Token)
   - Convert DFI (only for DFI)
4. Lighter image and updated display name for UTXO DFI

Send logic on send page still in progress. Need to add more validations. Marking it ready for review for Ivan to merge his convert screen.

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

<div>
<img width="30%" src="https://user-images.githubusercontent.com/25013382/124113713-52933880-da9e-11eb-88a8-aa1f74049798.jpg">
<img width="30%" src="https://user-images.githubusercontent.com/25013382/124113744-5cb53700-da9e-11eb-8aeb-a9872addafc8.jpg">
<img width="30%" src="https://user-images.githubusercontent.com/25013382/124113805-6dfe4380-da9e-11eb-8406-39557047b286.jpg">
<img width="30%" src="https://user-images.githubusercontent.com/25013382/124113832-76567e80-da9e-11eb-9304-379de7cc3022.jpg">
</div>

2021-07-02 07:48 UTC, ivan-zynesis submitted a review, later dismissed

2021-07-06 04:00 UTC, fuxingloh requested changes

2021-07-06 06:03 UTC, fuxingloh approved these changes

2021-07-06 06:03 UTC, fuxingloh commented on screens/AppNavigator/screens/BalancesScreen/BalancesNavigator.tsx
> +            headerTitle: () => {
You need to add `hide back title` to all navigation if you use an alternative header title. Or else it will clip on iOS.

2021-07-06 06:04 UTC, fuxingloh commented on screens/AppNavigator/screens/BalancesScreen/BalancesNavigator.tsx
> +            headerTitle: () => {
resolve in another PR

2021-07-06 06:16 UTC, merged