fix(ui-ux): Rectify grammatical error for "Collateral" (uncountable noun; no `s`)
DeFiCh/wallet pull request #2235
Opened 2022-02-22 01:39 UTC by chloezxyy

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
'Collaterals' is a grammar error, this PR fixes the grammatical error in UI to 'Collateral'.

#### Which issue(s) does this PR fixes?:

Fixes #1859

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-02-22 05:27 UTC, thedoublejay requested changes
Can you verify these files/screens?

- [ ] `The collateralization ratio represents the amount of collaterals` in DetailsTab.tsx
- [ ] ConfirmBorrowLoanTokenScreen
- [ ] ConfirmPaybackLoanScreen

2022-02-22 08:53 UTC, thedoublejay requested changes
For all updated translations, should we re-check if translations are still valid? Since we changed collaterals to singular form.

2022-02-23 09:32 UTC, kyleleow approved these changes

2022-02-23 09:48 UTC, thedoublejay approved these changes

2022-02-23 09:48 UTC, merged