Pierregee/redesign browse auctions
DeFiCh/wallet pull request #2360
Opened 2022-03-08 15:47 UTC by pierregee

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
- Redesign auction cards
- Add filtering - From your vault
- Add filtering - With placed bids
- Add sorting logic in the ff order:
        - Placed bid lost (if multiple time remaining)
        - Placed bid winning
        - From your vault
        - Time remaining 

#### Which issue(s) does this PR fixes?:

Fixes #1879

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-03-09 08:07 UTC, thedoublejay requested changes
There's a significant performance lag with this update. Maybe we need to re-check. 
1. Switching between Auctions, DEX and other tabs 
2. Switching to ALL tabs is causing slowness

2022-03-09 08:12 UTC, thedoublejay requested changes

2022-03-09 08:12 UTC, thedoublejay commented on mobile-app/app/screens/AppNavigator/screens/Auctions/components/BatchCard.tsx
> +            {batch?.highestBid?.owner !== address && batch.froms.some(bidder => bidder === address) &&
Should we store this on a variable and maybe memoized it? So it doesn't recheck on every re-render

2022-03-18 06:27 UTC, pierregee commented on mobile-app/app/screens/AppNavigator/screens/Auctions/components/BrowseAuctions.tsx
> +        {isBetaFeature('auction') &&
Removed in another PR

2022-08-31 06:29 UTC, closed without merging

2022-08-31 06:29 UTC, pierregee commented
The design has changed for auctions v2