feature(ui-ux): `DEX` - breakdown liquidity token
DeFiCh/wallet pull request #2517
Opened 2022-03-30 09:12 UTC by chloezxyy

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
To display the total liquidity tokens per DEX pair.

#### Which issue(s) does this PR fixes?:

Fixes #2334

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-03-31 04:18 UTC, kyleleow requested changes
Can you help to 
- remove the `(USD)` behind `Total liquidity (USD)`
- change the total liquidity in token value to `font-medium`
- change the color of usd value of total liquidity to match the token value

![image](https://user-images.githubusercontent.com/40191153/160975429-e0d0a142-61d2-4b9c-8429-b06f50579678.png)

2022-04-02 10:15 UTC, thedoublejay requested changes

2022-04-02 10:15 UTC, thedoublejay commented on mobile-app/app/screens/AppNavigator/screens/Dex/components/PoolPairCards/InfoSection.tsx
> +            lightTextStyle={isTitle === true ? tailwind('text-black') : undefined}
Our tailwind uses class-names for conditional statements. You can do something like this:

```suggestion
            lightTextStyle={tailwind({ 'text-black': isTitle })}
```

2022-04-02 10:15 UTC, thedoublejay commented on mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/components/ActiveUSDValue.tsx
>              dark={tailwind('text-gray-400')}
add dark style here also

2022-04-04 03:09 UTC, thedoublejay approved these changes

2022-04-04 03:10 UTC, merged