feature(ui-ux): add CTA to future swap from portfolio screen
DeFiCh/wallet pull request #2572
Opened 2022-04-06 01:43 UTC by kyleleow

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
- To add UI component for CTA to future swap from portfolio screen
- To add list view UI
- To add detail view UI

#### Which issue(s) does this PR fixes?:

Fixes #2569 
Fixes #2570 
Fixes #2571 

#### Additional comments?:
- UI only, by default CTA is hidden, to supper backward compatibility if merged
- Tests will be added after API/logic integration
![image](https://user-images.githubusercontent.com/40191153/161878573-e5f4ba39-68a5-481a-bade-0b1dac1e2a4d.png)
![image](https://user-images.githubusercontent.com/40191153/161878591-85d66612-c894-4f84-8fe1-15cde13966d5.png)
![image](https://user-images.githubusercontent.com/40191153/161878610-71e80438-0827-406c-abdc-b9106b0488c7.png)

#### Developer Checklist:

- [x] Read your code changes at least once
- [x] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [x] No console errors on web
- [x] Tested on Light mode and Dark mode*
- [x] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-04-06 12:41 UTC, pierregee requested changes

2022-04-06 12:41 UTC, pierregee commented on mobile-app/app/screens/AppNavigator/screens/Balances/BalancesScreen.tsx
> +            {translate('screens/BalancesScreen', '{{number}} pending future swaps', { number: 2 })}
Let's also handle singular/plural of `swaps` based on `{number}`

2022-04-06 13:30 UTC, pierregee commented on mobile-app/app/screens/AppNavigator/screens/Balances/screens/FutureSwapScreen.tsx
> +import tailwind from 'tailwind-rn'
```suggestion
import { tailwind } from '@tailwind'
```

2022-04-07 05:47 UTC, kyleleow commented on mobile-app/app/screens/AppNavigator/screens/Balances/screens/FutureSwapDetailScreen.tsx
> +export function FutureSwapDetailScreen ({ route }: Props): JSX.Element {
Yea its different from figma, but considering all our other confirm-related screen, we have the same UI element but without top border, so i wanted to keep it consistent.

2022-04-14 06:17 UTC, pierregee approved these changes

2022-04-14 06:17 UTC, merged