fix(ui-ux): `balances` align TokenAmountText on the right
DeFiCh/wallet pull request #2662
Opened 2022-04-19 06:47 UTC by chloezxyy

#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-04-19 06:48 UTC, thedoublejay commented
Let's include this next release

2022-04-19 06:49 UTC, chloezxyy commented
Token amount should be aligned to the right even if token value text is longer than token amount text

![image](https://user-images.githubusercontent.com/44501120/163942727-68625d4f-adc2-4fba-8c3a-626f7b39e2c7.png)

2022-04-20 06:33 UTC, pierregee requested changes
LGTM, just need to update the unit test

2022-04-21 05:46 UTC, pierregee approved these changes

2022-04-21 08:49 UTC, merged