style(ui-ux): update design of prices
DeFiCh/wallet pull request #2673
Opened 2022-04-20 10:47 UTC by pierregee

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
- Update the design of prices section - add/remove liquidity (to be with swap screen)
- Create function for repetitive tests related to prices
- Move the PriceSection component from DEX folder to components
- Move the translations of PriceSection on its own

#### Which issue(s) does this PR fixes?:

Fixes #2595

#### Additional comments?:
- Future swap feature has some updates in price rates section for swap. Thus, it would be inconsistent again once it's been released. We'll iterate over other pages once the Future Swap has been released

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-04-22 04:33 UTC, fullstackninja864 requested changes

2022-04-22 04:33 UTC, fullstackninja864 commented on mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreen.tsx
> +import { PriceRateProps, PricesSection } from '../../../../../components/PricesSection'
can use `@components/PricesSection`

2022-04-22 04:33 UTC, fullstackninja864 commented on mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/ConfirmCompositeSwapScreen.tsx
> +import { PricesSection } from '../../../../../components/PricesSection'
can use `@components/PricesSection`

2022-04-22 04:33 UTC, fullstackninja864 commented on shared/translations/languages/de.json
> +}
please add new line

2022-04-22 09:40 UTC, pierregee commented on mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/ConfirmCompositeSwapScreen.tsx
> +import { PricesSection } from '../../../../../components/PricesSection'
Updated!

2022-04-22 09:40 UTC, pierregee commented on mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreen.tsx
> +import { PriceRateProps, PricesSection } from '../../../../../components/PricesSection'
Updated!

2022-04-22 09:41 UTC, pierregee commented on shared/translations/languages/de.json
> +}
Updated!

2022-04-25 02:46 UTC, fullstackninja864 submitted a review, later dismissed

2022-04-25 07:46 UTC, thedoublejay requested changes
Prices are displayed wrong.

2022-04-25 08:13 UTC, pierregee commented
> Prices are displayed wrong.

Updated!

2022-04-25 09:11 UTC, merged