Add ES and IT translation
DeFiCh/wallet pull request #2688
Opened 2022-04-22 06:48 UTC by Kolibri1990

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
Add Italian and Spanish translation

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:
Translation of the DFX wallet from our native moderators
#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-04-22 08:00 UTC, thedoublejay commented
Hi @Kolibri1990 thanks for this. Will ask them to be reviewed first

2022-04-22 10:56 UTC, Kolibri1990 commented
@thedoublejay no problem. 
I have already some minor fixes in the translations... the moderators also translated the variables and I have found some typos.
How should I go on for that?

2022-04-25 10:38 UTC, hidiego requested changes

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "What do the different statuses of a vault mean?": "¿Qué significas los distintos estados de la bóveda?",
```suggestion
    "What do the different statuses of a vault mean?": "¿Qué significan los distintos estados de la bóveda?",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "Add to liquidity pool": "Añadir a la piscina de liquidez",
```suggestion
    "Add to liquidity pool": "Añadir a la pool de liquidez",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "DFIs in token form are used for various DeFiChain functions such as Liquidity Pools, Loans, Auctions and DEX swaps.": "DFI en forma de token se utilizan para fondos de liquidez, préstamos, subas
```suggestion
    "DFIs in token form are used for various DeFiChain functions such as Liquidity Pools, Loans, Auctions and DEX swaps.": "DFI en forma de token se utilizan para pools de liquidez, préstamos, subastas e intercambios.",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "Liquidity pools": "Fondos de liquidez",
```suggestion
    "Liquidity pools": "Pools de liquidez",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "https://dfx.swiss/en/terms/": "https://dfx.swiss/es/terminos/"
```suggestion
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "You have unsaved changes. Are you sure to discard them and leave the screen?": "Tu has hecho cambios que no se han guardado. ¿Estás seguro de que quieres descartarlos y dejar la pantalla actual?
```suggestion
    "You have unsaved changes. Are you sure to discard them and leave the screen?": "Hay cambios que no se han guardado. ¿Estás seguro de que quieres descartarlos y dejar la pantalla actual?",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "Feature is still in Beta. Use at your own risk.": "Estas características están aún en prueba. Usalas a tu propio riesgo."
```suggestion
    "Feature is still in Beta. Use at your own risk.": "Estas características están aún en prueba. Úsalas a tu propio riesgo."
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "Portfolio": "Portfalio",
```suggestion
    "Portfolio": "Portafolio",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "QUICK BID": "OFERTA RAPIDA",
```suggestion
    "QUICK BID": "OFERTA RÁPIDA",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "TRANSACTION DETAILS": "DETALLES DE LA TRANSACCION",
```suggestion
    "TRANSACTION DETAILS": "DETALLES DE LA TRANSACCIÓN",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "MIN. BID": "MINIMA OFERTA",
```suggestion
    "MIN. BID": "OFERTA MÍNIMA",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "You are about to close vault {{vaultId}}": "Tu estás a punto de cerrar la bóveda {{vaultId}}",
```suggestion
    "You are about to close vault {{vaultId}}": "Estás a punto de cerrar la bóveda {{vaultId}}",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "CONVERTING": "CONVERTIENDO",
```suggestion
    "CONVERTING": "CONVIRTIENDO",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "You are editing scheme of vault": "Tu estás editando el tipo de bóveda",
```suggestion
    "You are editing scheme of vault": "Estás editando el tipo de bóveda",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "Make sure your collateralization ratio is still above your min. collateralization ratio": "Asegúarate de que el ratio de colateralización está todavía por arriba del ratio mínimo de colateraliza
```suggestion
    "Make sure your collateralization ratio is still above your min. collateralization ratio": "Asegúarate de que el ratio de colateralización está todavía por encima del ratio mínimo de colateralización",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "TRANSACTION RESULTS": "RESULTADOS DE LA TRANSACCION",
```suggestion
    "TRANSACTION RESULTS": "RESULTADOS DE LA TRANSACCIÓN",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "VAULT DETAILS": "DETALLES DE LA BOVEDA",
```suggestion
    "VAULT DETAILS": "DETALLES DE LA BÓVEDA",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "TRANSACTION DETAILS": "DETALLES DE LA TRANSACCION",
```suggestion
    "TRANSACTION DETAILS": "DETALLES DE LA TRANSACCIÓN",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "SELECT LOAN TOKEN": "SELECCIONA UN TOKEN PARA EL PRESTAMO",
```suggestion
    "SELECT LOAN TOKEN": "SELECCIONA UN TOKEN PARA EL PRÉSTAMO",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "TRANSACTION DETAILS": "DETALLES DE LA TRANSACCION",
```suggestion
    "TRANSACTION DETAILS": "DETALLES DE LA TRANSACCIÓN",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "You are paying": "Tu estás pagando",
```suggestion
    "You are paying": "Estás pagando",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "You are paying": "Tu estás pagando",
```suggestion
    "You are paying": "Estás pagando",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "VAULT IN USE": "BOVEDA EN USO",
```suggestion
    "VAULT IN USE": "BÓVEDA EN USO",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "YOU ARE PAYING FOR LOAN": "TU ESTAS PAGANDO EL PRESTAMO",
```suggestion
    "YOU ARE PAYING FOR LOAN": "ESTÁS PAGANDO EL PRÉSTAMO",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "CONFIRM ADD COLLATERAL": "CONFIRMA LA ADICION DEL COLATERAL",
```suggestion
    "CONFIRM ADD COLLATERAL": "CONFIRMA LA ADICIÓN DEL COLATERAL",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "You are adding collateral to": "Tu estás añadiendo colateral a",
```suggestion
    "You are adding collateral to": "Estás añadiendo colateral a",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "COLLATERALIZATION DETAILS": "DETALLES DE LA COLATERALIZACION",
```suggestion
    "COLLATERALIZATION DETAILS": "DETALLES DE LA COLATERALIZACIÓN",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "Active loans": "Préstamos activso",
```suggestion
    "Active loans": "Préstamos activos",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "LOAN SCHEME": "TIPO DE PRESTAMO",
```suggestion
    "LOAN SCHEME": "TIPO DE PRÉSTAMO",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "BROWSE LOAN TOKENS": "BUSCA TOKENS PARA EL PRESTAMO"
```suggestion
    "BROWSE LOAN TOKENS": "BUSCA TOKENS PARA EL PRÉSTAMO"
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "EDIT LOAN SCHEME": "EDITA EL TIPO DE PRESTAMO",
```suggestion
    "EDIT LOAN SCHEME": "EDITA EL TIPO DE PRÉSTAMO",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "CONFIRM CREATE VAULT": "CONFIRMA LA CREACION DE UNA BOVEDA",
```suggestion
    "CONFIRM CREATE VAULT": "CONFIRMA LA CREACIÓN DE UNA BOVEDA",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "VAULT DETAILS": "DETALLES DE LA BOVEDA",
```suggestion
    "VAULT DETAILS": "DETALLES DE LA BÓVEDA",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "TRANSACTION DETAILS": "DETALLES DE LA TRANSACCION",
```suggestion
    "TRANSACTION DETAILS": "DETALLES DE LA TRANSACCIÓN",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "You are creating vault": "Tu estás creando una bóveda",
```suggestion
    "You are creating vault": "Estás creando una bóveda",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "Confirm your vault details in next screen": "Confirmalos detalles de tu bóveda en la siguiente pantalla",
```suggestion
    "Confirm your vault details in next screen": "Confirma los detalles de tu bóveda en la siguiente pantalla",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "CREATE VAULT": "CREA BOVEDA"
```suggestion
    "CREATE VAULT": "CREA BÓVEDA"
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "EMPTY": "VACIO",
```suggestion
    "EMPTY": "VACÍO",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "IN LIQUIDATION": "EN LIQUIDACION",
```suggestion
    "IN LIQUIDATION": "EN LIQUIDACIÓN",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "Auction ended": "Se acabo la subasta"
```suggestion
    "Auction ended": "Subasta finalizada"
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "VAULT DETAILS": "DETALLES DE LA BOVEDA",
```suggestion
    "VAULT DETAILS": "DETALLES DE LA BÓVEDA",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "Manage bids": "Gestiona ofertas",
```suggestion
    "Manage bids": "Gestionar ofertas",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "TRANSACTION RESULTS": "RESULTADOS DE LA TRANSACCION",
```suggestion
    "TRANSACTION RESULTS": "RESULTADOS DE LA TRANSACCIÓN",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "CONVERSION DETAILS": "DETALLES DE LA CONVERSION",
```suggestion
    "CONVERSION DETAILS": "DETALLES DE LA CONVERSIÓN",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "Can I send liquidity pool tokens to an exchange or another entity?": "¿Puedo enviar token de la piscina de liquidez a un exchange o a otra entidad?",
```suggestion
    "Can I send liquidity pool tokens to an exchange or another entity?": "¿Puedo enviar token de la pool de liquidez a un exchange o a otra entidad?",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "After deciding which pool pair you would like to supply liquidity to, click ADD LIQUIDITY and enter the input amount for either of the tokens in the pair.\n\nOnce an amount is entered on one sid
```suggestion
    "After deciding which pool pair you would like to supply liquidity to, click ADD LIQUIDITY and enter the input amount for either of the tokens in the pair.\n\nOnce an amount is entered on one side of the pair, the app automatically balances the amount of the other side, based on the ratio of current liquidity in the pool.": "Despúes de decidir a que pool vas a aportar liquidez, apreta AÑADIR LIQUIDEZ, y escribe la cantidad de cada uno de los tokens que quieres aportar. \n\nUna vez escribas la cantidad de un token, la app calculará automáticamente la cantidad del otro token para que tengan un valor igual, basado en el ratio de liquidez que tenga la pool en ese momento.",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "Swapping {{amountA}} {{symbolA}} to {{amountB}} {{symbolB}}": "Intercambiando {{amountA}} {{symbolA}} a {{amountB}} {{symbolB}}",
```suggestion
    "Swapping {{amountA}} {{symbolA}} to {{amountB}} {{symbolB}}": "Intercambiando {{amountA}} {{symbolA}} por {{amountB}} {{symbolB}}",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "CONFIRM SWAP": "CONFIRMACION DEL INTERCAMBIO",
```suggestion
    "CONFIRM SWAP": "CONFIRMAR EL INTERCAMBIO",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "You have": "Tu tienes",
```suggestion
    "You have": "Tienes",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "You will receive": "Tu recibirás"
```suggestion
    "You will receive": "Recibirás"
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "YOU ARE CURRENTLY CONNECTED TO": "TU ESTAS CONECTADO ACTUALMENTE A",
```suggestion
    "YOU ARE CURRENTLY CONNECTED TO": "ESTÁS CONECTADO ACTUALMENTE A",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "TRANSACTION DETAILS": "DETALLES DE LA TRANSACCION",
```suggestion
    "TRANSACTION DETAILS": "DETALLES DE LA TRANSACCIÓN",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "Your pooled {{symbol}}": "Tus {{symbol}} en la piscina",
```suggestion
    "Your pooled {{symbol}}": "Tus {{symbol}} en la pool",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "Share of pool": "Porcentaje de la piscina",
```suggestion
    "Share of pool": "Participaciones en la pool",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "TRANSACTION DETAILS": "DETALLES DE LA TRANSACCION",
```suggestion
    "TRANSACTION DETAILS": "DETALLES DE LA TRANSACCIÓN",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "TRANSACTION DETAILS": "DETALLES DE LA TRANSACCION",
```suggestion
    "TRANSACTION DETAILS": "DETALLES DE LA TRANSACCIÓN",
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "TRY AGAIN": "VUELVELO A INTENTAR"
```suggestion
    "TRY AGAIN": "VOLVER A INTENTAR"
```

2022-04-25 10:38 UTC, hidiego commented on shared/translations/languages/es.json
> +    "You have denied the permission request to use your camera": "Tu has denegado el acceso de uso a tu cámara"
```suggestion
    "You have denied the permission request to use your camera": "Has denegado el acceso de uso a tu cámara"
```

2022-05-04 01:30 UTC, merged