feature(ui-ux): `translations` - add option for es and it translations
DeFiCh/wallet pull request #2724
Opened 2022-04-27 05:55 UTC by chloezxyy

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
- [ ]  Add option on language list in settings page
- [ ] Display translated labels

#### Which issue(s) does this PR fixes?:

Fixes #2696

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-04-28 06:49 UTC, pierregee commented
Is there a shorter text for `SWAP` in Español?, it seems to be cut right now. Or else we might need handle it in the UI

Android: ![image](https://user-images.githubusercontent.com/13292662/165693335-eeeacedc-f7e2-488f-be47-54802270397f.png)

2022-04-28 06:59 UTC, fullstackninja864 commented
<img src="https://user-images.githubusercontent.com/53080940/165695158-989f0293-dcd5-4b17-a224-5ee2cd0694d2.png" width="30%"/>
Can we recheck these type of hidden text issue on all screen please

2022-04-28 07:00 UTC, fullstackninja864 requested changes

2022-04-28 07:00 UTC, fullstackninja864 commented on shared/translations/languages/es.json
> +        "Guidelines": "Instrucciones",
use 2 space indentation

2022-04-28 07:00 UTC, fullstackninja864 commented on shared/translations/languages/es.json
> +}
add new line at end

2022-04-28 07:00 UTC, fullstackninja864 commented on shared/translations/languages/it.json
> +        "Guidelines": "Linee guida",
use 2 space indentation

2022-04-28 07:00 UTC, fullstackninja864 commented on shared/translations/languages/it.json
> +}
new line at end

2022-04-28 07:36 UTC, chloezxyy commented
Modified :)

![image](https://user-images.githubusercontent.com/44501120/165701464-c9407140-3daa-4411-92f0-63f29d3a3d32.png)

2022-04-28 09:17 UTC, chloezxyy commented
Updated translations for shorter text mainly for for Spanish and title of DEX page for Italian
![Screenshot 2022-04-28 at 5 17 08 PM](https://user-images.githubusercontent.com/44501120/165720373-a6edff64-b0e3-4a14-8ca9-6ef3383613d2.png)

2022-05-04 10:26 UTC, thedoublejay approved these changes

2022-05-04 10:26 UTC, merged