token detail - reenable for DFI #2395 (#2758)
DeFiCh/wallet pull request #2770
Opened 2022-05-11 11:35 UTC by thedoublejay

* token detail - reenable for DFI #2395

* token detail - reenable for DFI #2395

* token detail - reenable for DFI #2395

#### What kind of PR is this?:

/kind

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-05-11 11:44 UTC, thedoublejay commented
@rox1338 I have moved your PR here so we can run the tests. Some additional changes:
1. Can you change the onNavigateSwapDFI to use same method as onNavigateSwap? Maybe make the params optional so we don't recreate the same method. The usage is the same also.

Once #1 is done, you don't need to setIsFromToken anymore since it's passed as a parameter.

You can create the PR to this branch

2022-05-12 07:39 UTC, rox1338 commented
https://github.com/DeFiCh/wallet/pull/2772

2022-05-13 06:42 UTC, thedoublejay commented
@rox1338 there's a type error on your last commit

2022-05-13 10:42 UTC, rox1338 requested changes

2022-05-13 10:42 UTC, rox1338 commented on mobile-app/app/screens/AppNavigator/screens/Balances/screens/TokenDetailScreen.tsx
> +  const onNavigateSwap = ({ pair, fromToken }: { pair: PoolPairData, fromToken: WalletToken }): void => {
```suggestion
  const onNavigateSwap = ({ pair, fromToken }: { pair?: PoolPairData, fromToken?: WalletToken }): void => {
```

2022-05-16 06:52 UTC, rox1338 commented on mobile-app/app/screens/AppNavigator/screens/Balances/screens/TokenDetailScreen.tsx
> +  const onNavigateSwap = ({ pair, fromToken }: { pair: PoolPairData, fromToken: WalletToken }): void => {
@thedoublejay that should fix it
I think you can commit it using github

2022-05-17 06:09 UTC, rox1338 commented on mobile-app/app/screens/AppNavigator/screens/Balances/screens/TokenDetailScreen.tsx
> +
```suggestion
```

2022-05-17 06:10 UTC, rox1338 commented on mobile-app/app/screens/AppNavigator/screens/Balances/screens/TokenDetailScreen.tsx
> +
For some reason this didn't get deleted. Must be some merge problem or sth.

2022-05-17 07:14 UTC, thedoublejay commented
@rox1338 Some comments:

1. Token Detail - DeFiChain token link is wrong - when opening DeFiScan
2, Portfolio - DFI Border card is not rounded anymore 

When creating PR, please ensure that all changes will not cause a regression issue and it's well tested. Thanks!

2022-05-17 11:36 UTC, rox1338 commented
@thedoublejay I always try to test my changes. Sometimes I probably don't have the eye for some details as I am not as experienced with the codebase as you are.
@1: Didn't try that link because I didn't expect a problem here.
@2: I didn't see that because I used the bright theme.
@3: I tried to change the touch area to be the same as with the other cards. I think that is what you meant?

I tried to fix all the things and created a PR #2788 

Regarding the convert-button: Do we want to have both options "Convert to UTXO" and "Convert to Token" in the DFI token details? Or just one button called "Convert"? Or the way it is now: 1 button "Convert to UTXO"?
<img width="478" alt="image" src="https://user-images.githubusercontent.com/100290452/168801996-47af05f4-80b4-4a36-a24e-7f7b58c07ea7.png">

2022-05-18 02:12 UTC, thedoublejay commented
> @thedoublejay I always try to test my changes. Sometimes I probably don't have the eye for some details as I am not as experienced with the codebase as you are. @1: Didn't try that link because I didn't expect a problem here. @2: I didn't see that because I used the bright theme. @3: I tried to change the touch area to be the same as with the other cards. I think that is what you meant?
> 
> I tried to fix all the things and created a PR #2788
> 
> Regarding the convert-button: Do we want to have both options "Convert to UTXO" and "Convert to Token" in the DFI token details? Or just one button called "Convert"? Or the way it is now: 1 button "Convert to UTXO"? <img alt="image" width="478" src="https://user-images.githubusercontent.com/100290452/168801996-47af05f4-80b4-4a36-a24e-7f7b58c07ea7.png">

@rox1338 Thanks for the prompt reply and changes. Don't get me wrong, I highly appreciate your contribution. Just wanted to align that testing is important, regardless of being experienced with codebase or not. It's ok we can keep it as Convert to UTXO first. Thanks again! Will test now

2022-05-18 02:38 UTC, merged