feature(ui-ux): add new header title and wallet stacks v2
DeFiCh/wallet pull request #3026
Opened 2022-06-22 09:40 UTC by kyleleow

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
- To add new header title
- To add wallet stacks v2 that will uses the new header title

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [x] Read your code changes at least once
- [x] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [x] No console errors on web
- [x] Tested on Light mode and Dark mode*
- [x] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-06-23 02:29 UTC, thedoublejay requested changes

2022-06-23 02:29 UTC, thedoublejay commented on mobile-app/app/screens/Main.web.tsx
> +    <SafeAreaProvider>
didn't we have this already somewhere?

2022-06-23 02:30 UTC, thedoublejay requested changes

2022-06-23 02:30 UTC, thedoublejay commented on mobile-app/app/constants/Theme.ts
> -      primary: isLight ? '#ff00af' : '#EE2CB1',
wouldn't this cause regression issues?

2022-06-23 02:33 UTC, kyleleow commented on mobile-app/app/screens/Main.web.tsx
> +    <SafeAreaProvider>
We have it on `Main.tsx` but not on web

2022-06-23 07:03 UTC, kyleleow commented on mobile-app/app/constants/Theme.ts
> -      primary: isLight ? '#ff00af' : '#EE2CB1',
updated

2022-06-25 02:44 UTC, thedoublejay approved these changes

2022-06-25 02:44 UTC, merged