feature(ui-ux): added wallet accordion, password and recovery word FAQ screen
DeFiCh/wallet pull request #3065
Opened 2022-06-28 05:07 UTC by fullstackninja864

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
This PR contains
- Wallet accordion redesign
- Passcode FAQ Screen 
- Recovery FAQ Screen 

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-06-29 03:46 UTC, kyleleow commented on mobile-app/app/screens/WalletNavigator/WalletNavigator.tsx
> +        <WalletStack.Screen
```suggestion
        <WalletStackV2.Screen
```

2022-06-29 03:47 UTC, kyleleow commented on mobile-app/app/screens/WalletNavigator/WalletNavigator.tsx
> +        <WalletStack.Screen
```suggestion
        <WalletStackV2.Screen
```

2022-06-30 00:38 UTC, thedoublejay requested changes

2022-06-30 00:38 UTC, thedoublejay commented on mobile-app/app/screens/WalletNavigator/screens/CreateWallet/PasscodeFaqV2.tsx
> +        {translate('components/PasscodeFaq', 'Your six-digit numeric code passcode, set by you, would be used to authorize all transactions. Keep your passcode private and secure. You are responsible
Maybe better to change to `Your six-digit numeric passcode`

2022-06-30 00:39 UTC, thedoublejay commented on mobile-app/app/screens/WalletNavigator/screens/CreateWallet/PasscodeFaqV2.tsx
> +        {translate('components/PasscodeFaq', 'Your six-digit numeric code passcode, set by you, would be used to authorize all transactions. Keep your passcode private and secure. You are responsible
Let's resolve this on another PR @fullstackninja864

2022-06-30 00:39 UTC, merged