feature(ui-ux): bottom navigation 2
DeFiCh/wallet pull request #3125
Opened 2022-07-07 08:15 UTC by thedoublejay

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-07-07 13:42 UTC, fullstackninja864 requested changes

2022-07-08 05:37 UTC, thedoublejay commented on mobile-app/app/screens/AppNavigator/BottomTabNavigator.tsx
> +              <AuctionsIcon
Will update it on another PR once everything is settled

2022-07-08 05:37 UTC, thedoublejay commented on mobile-app/app/screens/AppNavigator/BottomTabNavigator.tsx
> +          tabBarInactiveTintColor: isLight ? '#121212' : '#FFFFFF',
updated!

2022-07-08 05:37 UTC, thedoublejay commented on mobile-app/app/screens/AppNavigator/BottomTabNavigator.tsx
> +          tabBarActiveTintColor: '#FF008C',
updated!

2022-07-08 05:46 UTC, fullstackninja864 approved these changes

2022-07-08 05:52 UTC, merged