feature(ui-ux): add portfolio 2.0 header
DeFiCh/wallet pull request #3188
Opened 2022-07-19 08:43 UTC by kyleleow

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
- To update portfolio screen header, no bottom border is added for now to not create a separation with content in 2.0

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [x] Read your code changes at least once
- [x] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [x] No console errors on web
- [x] Tested on Light mode and Dark mode*
- [x] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-07-20 04:05 UTC, chloezxyy commented
<img width="429" alt="Screenshot 2022-07-20 at 12 03 54 PM" src="https://user-images.githubusercontent.com/44501120/179894309-7c174f46-f863-42bb-b2cb-d09d4749dc14.png">

Address label emoji's are slightly cut off on android

2022-07-20 09:45 UTC, kyleleow commented
It happens on certain combination of text and emoji, but not every time
![image](https://user-images.githubusercontent.com/40191153/179951899-e81abafe-b8a4-4fdc-9a5a-400675903650.png)

2022-07-20 10:30 UTC, pierregee requested changes

2022-07-20 10:35 UTC, pierregee commented on mobile-app/app/screens/AppNavigator/screens/Portfolio/PortfolioScreen.tsx
> +        <ThemedViewV2
will be handled in another pr

2022-07-21 03:32 UTC, thedoublejay requested changes
![Screenshot_20220721-113345_Expo Go](https://user-images.githubusercontent.com/25013382/180124226-d8889d8e-bb15-4de9-8dc4-55f9fad5dc8a.jpg)

Address Header is overflowing

2022-07-22 08:24 UTC, merged