feature(ui-ux): implemented action button portfolio 2.0
DeFiCh/wallet pull request #3196
Opened 2022-07-22 05:23 UTC by fullstackninja864

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-07-25 05:40 UTC, kyleleow commented on mobile-app/app/screens/AppNavigator/screens/Portfolio/components/ActionButtons.tsx
> +  if (isFeatureAvailable('future_swap')) {
i think if there is no future swap, the button will not be display too, according to figma

2022-07-26 01:07 UTC, kyleleow commented on mobile-app/app/screens/AppNavigator/screens/Portfolio/components/ActionButtons.tsx
> +        name: 'Convert',
Should navigate to composite swap screen

2022-07-26 06:53 UTC, kyleleow commented on mobile-app/app/screens/AppNavigator/screens/Portfolio/PortfolioScreen.tsx
>          <BalanceActionSection navigation={navigation} isZeroBalance={isZeroBalance} />
let's remove the old one

2022-07-26 10:21 UTC, kyleleow commented on mobile-app/app/screens/AppNavigator/screens/Portfolio/components/ActionButtons.tsx
> +      badge: futureSwaps.length > 9 ? '9+' : futureSwaps.length + 1,
i think we dont need to +1 right?
```suggestion
      badge: futureSwaps.length > 9 ? '9+' : futureSwaps.length,
```

2022-07-26 11:09 UTC, kyleleow commented on mobile-app/app/screens/AppNavigator/screens/Portfolio/PortfolioScreen.tsx
>          {hasPendingFutureSwap && <FutureSwapCta navigation={navigation} />}
we can remove this now

2022-07-27 02:35 UTC, kyleleow commented on mobile-app/app/screens/AppNavigator/screens/Portfolio/components/ActionButtons.tsx
> +  iconType: IconType
add `iconSize` to customize size for icons

2022-07-27 02:36 UTC, kyleleow commented on mobile-app/app/screens/AppNavigator/screens/Portfolio/components/ActionButtons.tsx
> +          size={28}
add `style={tailwind('ml-px')}`

2022-07-29 06:19 UTC, thedoublejay requested changes

2022-07-29 06:19 UTC, thedoublejay commented on mobile-app/app/screens/AppNavigator/screens/Portfolio/components/ActionButtons.tsx
> +  if (isFeatureAvailable('future_swap') && futureSwaps.length > 0) {
@fullstackninja864 I feel this one is more expensive. What if we just use if statements for rendering?

2022-07-29 07:22 UTC, thedoublejay approved these changes

2022-07-29 07:23 UTC, merged