font updates
DeFiCh/wallet pull request #322
Opened 2021-07-22 09:10 UTC by thedoublejay

#### What kind of PR is this?:

/kind chore

#### What this PR does / why we need it:
1. Use IBMPlexSans as global font
2. Created Text component to be used with new font
#### Which issue(s) does this PR fixes?:

Fixes #296 

#### Additional comments?:

2021-07-22 13:10 UTC, fuxingloh requested changes

2021-07-22 13:10 UTC, fuxingloh commented on app/components/Text.tsx
> +    fontWeight: '400',
can this be automatically be handled by `tailwind`?

2021-07-22 13:10 UTC, fuxingloh commented on app/components/Text.tsx
> +export const HeaderFont = { headerTitleStyle: { fontFamily: FontFaces.SemiBoldFont } }
can this be automatically be handled by tailwind within the Navigator that needs it?

2021-07-23 01:04 UTC, thedoublejay commented
@fuxingloh  I have created a new branch. Please use this link for the new PR - https://github.com/DeFiCh/wallet/pull/325

2021-07-23 01:04 UTC, closed without merging