feature(ui-ux): transaction card component 2.0
DeFiCh/wallet pull request #3227
Opened 2022-07-29 08:33 UTC by chloezxyy

#### What kind of PR is this?:

/kind

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-07-29 09:22 UTC, pierregee requested changes

2022-07-29 09:22 UTC, pierregee commented on mobile-app/app/screens/AppNavigator/screens/Dex/components/TransactionCard.tsx
> +      style={tailwind('rounded-lg-v2 px-4 py-4')}
```suggestion
      style={tailwind('rounded-lg-v2 p-4')}
```

2022-07-29 09:22 UTC, pierregee commented on mobile-app/app/components/TransactionCard.tsx
> +  current: string
```suggestion
  value: string
```

2022-07-29 09:22 UTC, pierregee commented on mobile-app/app/components/TransactionCard.tsx
> +  balance: BigNumber
```suggestion
  maxValue: BigNumber
```
just to be more generic with the naming

2022-07-29 09:44 UTC, pierregee submitted a review, later dismissed

2022-08-01 01:42 UTC, pierregee submitted a review, later dismissed

2022-08-01 01:42 UTC, thedoublejay commented
@pierregee @chloezxyy let's merge this after the release

2022-08-04 00:22 UTC, pierregee commented on mobile-app/app/components/TransactionCard.tsx
> +        style={tailwind('pl-5 pr-5 pt-2 mr-px rounded-t-lg-v2')}
```suggestion
        style={tailwind('rounded-t-lg-v2')}
```
to make way for other designs, let's move the padding and margins in `{children}` e.g send

2022-08-04 00:24 UTC, pierregee commented on mobile-app/app/components/TransactionCard.tsx
> +        style={tailwind('flex flex-row justify-around items-center pt-2 pb-4 border-t-0.5')}
```suggestion
        style={tailwind('flex flex-row justify-around items-center pb-4')}
```
send has no border, can we move this on `{children}` bottom border too?

2022-08-10 05:46 UTC, closed without merging