feature(ui-ux): add cancel prompt function on all transaction
DeFiCh/wallet pull request #3362
Opened 2022-08-25 04:19 UTC by G9000

#### What kind of PR is this?:
/kind feature

#### What this PR does / why we need it:
Adding cancel prompt functionality on the following transaction screen:

- Send
- Convert
- Add Liquidity
- Remove Liquidity
- Dex
- Auctions
- Loans

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-09-29 05:44 UTC, thedoublejay commented
@G9000 I will move this to next release

2022-10-12 06:20 UTC, pierregee commented
Bug:
1. Top up DUSD and DFI
2. Press top liquidity DUSD-DFI pool see screenshot
3. Add liquidity + continue and press cancel
4. Issue: Redirected back to Portfolio page
![image](https://user-images.githubusercontent.com/13292662/195264965-d7fef3e7-fb45-4318-9ff6-48405f86d809.png)

2022-10-12 06:25 UTC, pierregee requested changes

2022-10-12 06:25 UTC, pierregee commented on mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/ConfirmCompositeSwapScreen.tsx
> +                  ? "DexScreen"
Can use the enum `DexScreenOrigin.` here?

2022-10-12 06:25 UTC, pierregee commented on mobile-app/app/screens/AppNavigator/screens/Dex/DexConfirmRemoveLiquidity.tsx
> +                  ? "DexScreen"
same here

2022-10-17 03:35 UTC, pierregee commented on mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/ConvertConfirmationScreen.tsx
> +              navigation.navigate("PortfolioScreen");
can use enum here too

2022-10-17 03:35 UTC, pierregee commented on mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/SendConfirmationScreen.tsx
> +              navigation.navigate("PortfolioScreen");
here too

2022-10-17 03:41 UTC, pierregee requested changes
![image](https://user-images.githubusercontent.com/13292662/196084456-863e7921-5aab-4fff-a179-ffe8ed55cda6.png)
This warning is throwing on iOS

2022-10-25 05:35 UTC, pierregee approved these changes

2022-10-25 05:36 UTC, pierregee commented
1. add_liquidity.spec seems to be failing consistently after the cancel prompt
<img width="547" alt="image" src="https://user-images.githubusercontent.com/13292662/197690426-4bbd44d4-579b-488f-be1b-f24ed31c55ab.png">
can just fix in another PR

2022-10-25 05:37 UTC, merged