feature(ui-ux): Future Swap from portfolio v2
DeFiCh/wallet pull request #3371
Opened 2022-08-26 08:08 UTC by JoshuaC817

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
Update future swap screens from portfolio to v2 (listing and withdraw)

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-08-29 06:31 UTC, pierregee requested changes
Just some nitpicks and one bug that is existing in v1
![image](https://user-images.githubusercontent.com/13292662/187136429-645e807d-3091-46e6-ac2e-273dfa51d616.png)
Can disable the button if more than your future swap balance, it looks like it's a bug in v1. Let's fix it in v2 😱

2022-08-29 07:21 UTC, JoshuaC817 commented on mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/WithdrawFutureSwapScreenV2.tsx
> +    android: ['50%']
adjusted to 45% for both ios and android

2022-08-29 07:22 UTC, JoshuaC817 commented on mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/ViewSwapInfo.tsx
> +import { Platform, View } from 'react-native'
fixed the space below, couldn't reproduce the line on top, could you try again with the new changes?

2022-08-29 07:22 UTC, JoshuaC817 commented
> Just some nitpicks and one bug that is existing in v1 ![image](https://user-images.githubusercontent.com/13292662/187136429-645e807d-3091-46e6-ac2e-273dfa51d616.png) Can disable the button if more than your future swap balance, it looks like it's a bug in v1. Let's fix it in v2 😱

issue fixed

2022-08-30 03:16 UTC, pierregee submitted a review, later dismissed
LGTM! 🚀 
![image](https://user-images.githubusercontent.com/13292662/187340789-aff5cf4a-f727-41b0-a4bc-bf2c752e27c2.png)

2022-09-03 01:08 UTC, thedoublejay commented
Sorry need to update conflicts :D @JoshuaC817

2022-09-04 02:30 UTC, merged