feature(ui-ux): loans v2
DeFiCh/wallet pull request #3530
Opened 2022-09-21 10:54 UTC by chloezxyy

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-09-23 07:10 UTC, pierregee requested changes

2022-09-23 07:54 UTC, chloezxyy commented on mobile-app/app/hooks/useNavigatorHeaderStylesOption.tsx
> +import { StackNavigationOptions } from "@react-navigation/stack";
Yep we can do that, we'll shift the hook into the location that you've mentioned, but for the reusing code we can do it on another PR instead?

2022-09-23 08:02 UTC, JoshuaC817 commented on mobile-app/app/screens/WalletNavigator/screens/components/PaginationButton.tsx
> +        style={tailwind("font-normal-v2 text-center text-base")}
```suggestion
        style={tailwind("font-semibold-v2 text-center text-base")}
```

2022-09-23 08:02 UTC, JoshuaC817 commented on mobile-app/app/screens/WalletNavigator/screens/components/PaginationButton.tsx
> +      style={tailwind("rounded-2xl-v2 text-center py-2 px-4 border", {
```suggestion
      style={tailwind("rounded-2xl-v2 text-center py-3.5 px-4 border", {
```

2022-09-23 08:19 UTC, pierregee commented on mobile-app/app/hooks/useNavigatorHeaderStylesOption.tsx
> +import { StackNavigationOptions } from "@react-navigation/stack";
can do at same PR

2022-09-26 09:25 UTC, JoshuaC817 commented on mobile-app/app/screens/WalletNavigator/screens/components/PaginationButton.tsx
> +      style={tailwind("rounded-2xl-v2 text-center py-3.5 px-4 border", {
```suggestion
      style={tailwind("rounded-full text-center py-3.5 px-4 border", {
```

2022-09-27 03:28 UTC, pierregee approved these changes

2022-09-27 03:47 UTC, merged