feature(ui-ux): loans v2 bottom sheet search
DeFiCh/wallet pull request #3630
Opened 2022-10-07 10:24 UTC by chloezxyy

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-10-13 02:03 UTC, chloezxyy commented
- In loans.specs file there is a skipped test, need help with verifying

2022-10-13 09:53 UTC, pierregee requested changes

2022-10-13 09:53 UTC, pierregee commented on mobile-app/app/screens/AppNavigator/screens/Loans/components/BottomSheetLoanTokensList.tsx
> +    );
```suggestion
    return t.token.displaySymbol
      .toLowerCase()
      .includes(searchTerm.trim().toLowerCase());
```
can simplify it like this? whacha think

2022-10-13 10:12 UTC, chloezxyy commented on mobile-app/app/screens/AppNavigator/screens/Loans/components/BottomSheetLoanTokensList.tsx
> +    );
Looks better

2022-10-14 03:42 UTC, pierregee approved these changes

2022-10-14 03:47 UTC, merged

2022-10-14 03:47 UTC, pierregee commented
![image](https://user-images.githubusercontent.com/13292662/195757966-e371e111-0a83-4cf2-afae-7c61696de348.png)
As discussed, let's follow the design of the header in another PR