fix(ui-ux): refactor network screen navigation
DeFiCh/wallet pull request #3709
Opened 2022-10-25 04:01 UTC by G9000

#### What this PR does / why we need it:
- fix an issue where bottom tabs changes when we navigate to network screen

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

2022-10-26 02:07 UTC, pierregee requested changes

2022-10-26 02:07 UTC, pierregee commented on mobile-app/app/screens/AppNavigator/screens/Loans/LoansNavigator.tsx
> +    networkScreenPath: "NetworkSelectionScreenDex",
shouldn't be `NetworkSelectionScreenLoans`

2022-10-27 02:49 UTC, chloezxyy commented
`useNavigatorHeaderStylesOption` is no longer used due to my recent navigator header refactor D: would recommend it to be done in `useNavigatorScreenOptions`

2022-12-01 07:36 UTC, pierregee approved these changes

2022-12-01 07:38 UTC, merged