`onboarding` - create and verify step
DeFiCh/wallet pull request #381
Opened 2021-08-01 11:45 UTC by thedoublejay

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
Updated designs for `onboarding` - create and verify step.
Pending Onboarding stepper, will merge with Ivan's changes.
#### Which issue(s) does this PR fixes?:

Fixes #152 

#### Additional comments?:

https://user-images.githubusercontent.com/25013382/127769614-7e678a0d-5be2-4350-a62b-8ca0f03eaabd.mp4

2021-08-01 12:00 UTC, fuxingloh requested changes

2021-08-01 12:00 UTC, fuxingloh commented on package.json
> +    "array-shuffle": "^2.0.0",
https://lodash.com/docs/4.17.15#shuffle

2021-08-01 12:09 UTC, thedoublejay commented on package.json
> +    "array-shuffle": "^2.0.0",
updated

2021-08-02 03:13 UTC, fuxingloh approved these changes
@ivan-zynesis is working on the new encrypted flow might conflict with this. Should merge early.

2021-08-02 03:18 UTC, ivan-zynesis approved these changes

2021-08-02 03:20 UTC, merged