stepper's description misalignment
DeFiCh/wallet pull request #457
Opened 2021-08-06 11:07 UTC by kyleleow

#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:
- To fix stepper's description misalignment

#### Which issue(s) does this PR fixes?:

Fixes #450

2021-08-06 12:20 UTC, thedoublejay requested changes
![Screenshot_20210806-201923_Expo Go](https://user-images.githubusercontent.com/25013382/128509387-2ae8b2f5-f82e-4c57-ade7-5031dc71f0c0.jpg)
The text doesn't take full space, try to increase the width a bit. Also, reduce the margin top of the title with the stepper. It looks too spaced

2021-08-07 01:42 UTC, kyleleow commented
@thedoublejay works fine when i tested on web and ios device
![IMG_EF869E7465BF-1](https://user-images.githubusercontent.com/40191153/128584013-1f75d8f7-aa22-4533-8aaa-3c3feea1bdf9.jpeg)

I'll make some changes nevertheless

2021-08-07 01:48 UTC, thedoublejay commented
> @thedoublejay works fine when i tested on web and ios device
> ![IMG_EF869E7465BF-1](https://user-images.githubusercontent.com/40191153/128584013-1f75d8f7-aa22-4533-8aaa-3c3feea1bdf9.jpeg)
> 
> I'll make some changes nevertheless
> 

Ok thanks. For reference I'm testing it on S21 Ultra. Much bigger screen

2021-08-07 03:09 UTC, thedoublejay approved these changes

2021-08-07 03:09 UTC, merged